from fpdf import FPDF

def generate_gujarati_pdf(user_name, email, city, farm_size, crops, font_path=None):
    """
    Extremely simple Safe Mode PDF Generator.
    Uses standard Helvetica font and strips all non-Latin characters to ensure
    valid PDF generation and avoid corruption.
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14) # Standard Core Font

    # Helper to clean text for Core Fonts (Latin-1 only)
    def clean(text):
        if not text: return ""
        # Force conversion to simple ASCII/Latin-1, replacing unknown with ?
        return str(text).encode('latin-1', 'replace').decode('latin-1')

    # Header
    pdf.cell(0, 10, txt=clean("Krishi-Mitra AI - Farm Report"), ln=True, align='C')
    pdf.ln(5)

    # Body
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 10, txt=clean(f"Name: {user_name}"), ln=True)
    pdf.cell(0, 10, txt=clean(f"Email: {email}"), ln=True)
    pdf.cell(0, 10, txt=clean(f"City: {city}"), ln=True)
    pdf.cell(0, 10, txt=clean(f"Total Size: {farm_size} Acres"), ln=True)
    
    pdf.ln(5)
    pdf.cell(0, 10, txt=clean("Active Crops Status:"), ln=True)
    
    for crop in crops:
         line = f"- {crop.get('crop_name')} ({crop.get('area')} Ac): {crop.get('health_status')}"
         pdf.cell(0, 10, txt=clean(line), ln=True)

    # Footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 10, txt=clean("Generated by Krishi-Mitra AI (Safe Mode)"), ln=True)

    # Output - Handle FPDF versions carefully
    try:
        out = pdf.output() 
        if isinstance(out, str):
            # FPDF 1.7.x returns latin-1 string
            return True, out.encode('latin-1')
        # FPDF 2.x returns bytearray
        return True, bytes(out)
    except Exception as e:
        print(f"PDF Gen Output Error: {e}")
        # Return a tiny valid PDF as absolute last resort if standard fails
        return False, b""
