from fpdf import FPDF
import datetime
from io import BytesIO

class FarmReport(FPDF):
    def header(self):
        # Arial bold 15
        self.set_font('Arial', 'B', 15)
        # Title
        self.cell(0, 10, 'Krishi-Mitra AI: Farm Status Report', 0, 1, 'C')
        # Line break
        self.ln(5)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font('Arial', 'I', 8)
        # Page number
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'C')

def generate_farm_report(user_name, user_email, city, size, active_crops, live_data=None):
    """
    Generate a PDF report for the user's farm.
    """
    pdf = FarmReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # User Profile Section
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Farm Profile', 0, 1, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 7, f"Farmer Name: {user_name}", 0, 1, 'L')
    pdf.cell(0, 7, f"Email: {user_email}", 0, 1, 'L')
    pdf.cell(0, 7, f"Location: {city}", 0, 1, 'L')
    pdf.cell(0, 7, f"Global Farm Size: {size} Acres", 0, 1, 'L')
    pdf.cell(0, 7, f"Generated On: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1, 'L')
    pdf.ln(5)
    
    # Live Environment Section
    if live_data:
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'Micro-Climate & Environment', 0, 1, 'L')
        pdf.set_font('Arial', '', 10)
        w = live_data.get('weather', {})
        s = live_data.get('soil', {})
        pdf.cell(0, 7, f"Current Temperature: {w.get('temp', '--')}°C | Humidity: {w.get('humidity', '--')}%", 0, 1, 'L')
        pdf.cell(0, 7, f"Soil Moisture: {s.get('moisture', '--')}% | Soil Temp: {s.get('soil_temp', '--')}°C", 0, 1, 'L')
        pdf.ln(5)

    # Active Crops Section
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Active Crop Fields', 0, 1, 'L')
    pdf.ln(2)
    
    if not active_crops:
        pdf.set_font('Arial', 'I', 10)
        pdf.cell(0, 10, 'No active crops registered.', 0, 1, 'L')
    else:
        # Table Header
        pdf.set_font('Arial', 'B', 10)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(50, 8, 'Crop Name', 1, 0, 'C', 1)
        pdf.cell(30, 8, 'Area (Ac)', 1, 0, 'C', 1)
        pdf.cell(35, 8, 'Planting Date', 1, 0, 'C', 1)
        pdf.cell(35, 8, 'Chlorophyll', 1, 0, 'C', 1)
        pdf.cell(40, 8, 'Health Status', 1, 1, 'C', 1)
        
        # Table Body
        pdf.set_font('Arial', '', 9)
        for crop in active_crops:
            pdf.cell(50, 8, str(crop['crop_name']), 1, 0, 'C')
            pdf.cell(30, 8, str(crop['area']), 1, 0, 'C')
            pdf.cell(35, 8, str(crop['planting_date']), 1, 0, 'C')
            pdf.cell(35, 8, str(crop.get('chlorophyll', 'N/A')), 1, 0, 'C')
            pdf.cell(40, 8, str(crop.get('health_status', 'N/A')), 1, 1, 'C')

    # AI Recommendation Summary placeholder
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 8)
    pdf.multi_cell(0, 5, "Note: This report is generated by Krishi-Mitra AI. Plant health analysis is based on image processing and current environmental data. For critical farming decisions, please consult with an agricultural expert.")
    
    # Return PDF bytes
    return pdf.output(dest='S').encode('latin-1')
